version: '3.9'

services:
  gateway-service:
    build:
      dockerfile: apps/gateway-service/Dockerfile.prod
    env_file:
      - .env
    restart: always

  candidate-service:
    build:
      dockerfile: apps/candidate-service/Dockerfile.prod
    env_file:
      - .env
    restart: always

  parsing-service:
    build:
      dockerfile: apps/parsing-service/Dockerfile.prod
    env_file:
      - .env
    restart: always

  verification-service:
    build:
      dockerfile: apps/verification-service/Dockerfile.prod
    env_file:
      - .env
    restart: always

  qualification-service:
    build:
      dockerfile: apps/qualification-service/Dockerfile.prod
    env_file:
      - .env
    restart: always

  notification-service:
    build:
      dockerfile: apps/notification-service/Dockerfile.prod
    env_file:
      - .env
    restart: always