export const QR_GENERATOR = 'QR_GENERATOR';
export const HASH_SERVICE = 'HASH_SERVICE';
export const OBJECT_STORAGE = 'OBJECT_STORAGE';
export const QR_METADATA_REPOSITORY = 'QR_METADATA_REPOSITORY';
export const QR_CODE_GENERATION_POLICY = 'QR_CODE_GENERATION_POLICY';
