FROM node:22-bookworm-slim AS build
WORKDIR /src

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN rm -rf node_modules && npm ci --omit=dev

FROM public.ecr.aws/lambda/nodejs:22

ENV NODE_ENV=production

WORKDIR ${LAMBDA_TASK_ROOT}

COPY --from=build /src/package*.json ./
COPY --from=build /src/node_modules ./node_modules
COPY --from=build /src/dist ./dist

CMD ["dist/main.handler"]
