version: '3.9'

services:
  gateway-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start gateway-service --watch

  candidate-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start candidate-service --watch
  parsing-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start parsing-service --watch
  verification-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start verification-service --watch
  qualification-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start qualification-service --watch
  notification-service:
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nest start notification-service --watch