version: '3.9'

services:
  gateway-service:
    volumes:
      - .:/app
      - /app/node_modules

  candidate-service:
    volumes:
      - .:/app
      - /app/node_modules

  parsing-service:
    volumes:
      - .:/app
      - /app/node_modules

  verification-service:
    volumes:
      - .:/app
      - /app/node_modules

  qualification-service:
    volumes:
      - .:/app
      - /app/node_modules

  notification-service:
    volumes:
      - .:/app
      - /app/node_modules
